### ISSUE TITLE
azure serverless developer setup documentation

### ISSUE THREAD

**Issue by aaronhans** [cagov/API#1]
Great work getting this setup in azure and creating the deploy pipeline fro github already @carterm!

Please create an initial documentation set that would help a dev unfamiliar with this process get a new serverless function running using your process

I am available to run through the steps in the initial doc set to check if we need to augment them at all.

**Comment by abquirarte** [comment]
@carterm - love what you did with the function as a service feature!😄 
➕ on documentation plz!

**Comment by abquirarte** [comment]
Yay! thanks @carterm , is there a link?

**Comment by carterm** [comment]
The documentation displays on the readme.md file which renders in the root of this repository...
https://github.com/cagov/FunctionApps

**Comment by abquirarte** [comment]
✅

**Comment by abquirarte** [comment]
@carterm may be a good opportunity for a quick blog post on this? 😄 
CC: @jpetrucione
