### ISSUE TITLE
create API for lane closure data

### ISSUE THREAD

**Issue by aaronhans** [cagov/API#12]
Pull the lcs data from Caltrans every 5 minutes and reorganize it so it can power out client side application in the UX repo

**Comment by aaronhans** [comment]
- [x] new API available in azure production environment which returns lane closure data based on bounding box coordinates and route name parameters
- [x] read data from blob storage
- [x] add user documentation on how to pass bbox params and route names
- [x] API is available in the postman at api.alpha.ca.gov
- [x] add new endpoint to retrieve Caltans data every 5 minutes
- [x] add query to get the full road closures (use kml file until we get better directions from caltrans), add these to the API response
- [x] add query to get the chain controls (use kml file until we get better directions from caltrans), add these to response

**Comment by aaronhans** [comment]
working production endpoint: http://fa-go-alph-d-001.azurewebsites.net/LaneClosures/US-50?lat1=38.573832&lat2=38.956177&lon1=-121.490044&lon2=-119.942837&direction=East

**Comment by aaronhans** [comment]
Now we have 3 new APIs returning interesting near real time road information available at live FAAS endpoints in azure and documented on postman: https://documenter.getpostman.com/view/9918160/SWLb8Uep?version=latest#d5f75d04-de78-44e8-a227-2b3b00a11a5d

**Comment by aaronhans** [comment]
This task is complete. The postman documentation tools and resulting pages are pretty cool 

We do a lot more as far as documenting these APIs. We are privileged to have the ear of some experienced advisors and hopefully we'll hear from them with some recommendations. We could also run our documentation strategies by our content design team or look into Worth looking into stuff like https://konghq.com/blog/leveraging-openapi-awesome-apis/ we should research this and probably create some follow up tasks

**Comment by abquirarte** [comment]
✅ Sweet! We'll def want to do more of this.
