### ISSUE TITLE
Put Human Right to Water testing data into API

### ISSUE THREAD

**Issue by aaronhans** [cagov/API#19]
HR2W data is published every couple months here https://www.waterboards.ca.gov/water_issues/programs/hr2w/

We should:

<del>- [ ] Create automated process that pulls that dataset regularly and processes it into our API</del>
- [x] Allow people to retrieve full testing data with pwsid
- [x] Create endpoint that returns test results for system currently in violation based on pwsid
- [x] Return status info if there is no negative test results. That means the water leaving the plant has lower than government required testing level of all the analytes being tested
- [x] Optimize system lookup API by splitting geojson so lookups are faster
- [x] Fix system lookup bug that overwrites found result when there are multiple polygons
- [x] Show unsafe results for all types of contaminants
- [x] document the water APIs
- [x] add tests to APIs where they are missing
- [x] put Cron APIs in new repo
- [x] evaluate new service boundary dataset we got from Stephanie Bucknam
  I reviewed this dataset. It is great that this is improving but we aren't ready to migrate to it yet. It is missing some important systems. One big problem that sent us looking for better data was that Fresno search didn't return a system. We have Fresno in our dataset already but when mapbox returns the computed center of the city limits it gives us a point outside of the service boundary area of the city of fresno water system. If you enter an address in Fresno we get the right system back. So I recommend no immediate action now but check back in with Stephanie in a couple months to see how her data is evolving. We will be reviewing mapbox as an autocomplete service in the performance related tasks and can eval alternatives against Fresno for quality

**Comment by aaronhans** [comment]
Right now we have the latest data and can refresh it with scripts running locally. Ran into some interesting issues pulling the HR2W datasource with code: https://github.com/nodejs/node/issues/27711 need to run the script with flags to grab an older http parser because the water site is using headers with spacers which break latest node parsers so makes any retrieval method fail including request and server side fetch. I'm not sure yet how to get our script to run regularly on a lambda using these flags so we need to research this. I'd like to split that off into a separate issue and address it when we see a water data update (which also might break scripts if they change structure)

So postponing this issue: "Create automated process that pulls that dataset regularly and processes it into our API"

New issue to solve this: https://github.com/cagov/API/issues/23

**Comment by abquirarte** [comment]
great documentation- thank you Aaron
