### ISSUE TITLE
API service domain name

### ISSUE THREAD

**Issue by carterm** [cagov/API#2]
We should register a friendly name for alpha.ca.gov api services.

suggesting api.alpha.ca.gov?

The API service is located here...
https://fa-go-alph-d-002.azurewebsites.net/

a running sample api is here...
https://fa-go-alph-d-002.azurewebsites.net/ConnectionTest

**Comment by carterm** [comment]
@ChadABratton This is ready to go.  Can you request the domain name?

**Comment by ChadABratton** [comment]
DNS Request Draft:

CNAME | api.alpha.ca.gov | fa-go-alph-d-002.azurewebsites.net
TXT | api.alpha.ca.gov | fa-go-alph-d-002.azurewebsites.net
A | api.alpha.ca.gov | 40.112.192.69

**Comment by carterm** [comment]
This is done and ready for review.

Added production link to StateHolidays Demo...[Here](https://cagov.github.io/UX/state-holidays/)

API Doc site (redirect)...[Here](https://api.alpha.ca.gov)

API Hello world... [here](http://api.alpha.ca.gov/ConnectionTest)

**Comment by abquirarte** [comment]
Link to final domain for this service: 
api.alpha.ca.gov 

✅
