### ISSUE TITLE
Connect State Holiday to service to get next holiday

### ISSUE THREAD

**Issue by carterm** [cagov/API#20]
The next state holiday is hardcoded.  Create an API to get the next one and use it in the Alpha story.  The actual code can still be hardcoded for now.

Progress work for https://github.com/cagov/API/issues/7

**Comment by carterm** [comment]
https://github.com/cagov/Alpha/pull/338

**Comment by carterm** [comment]
Live API service is running [here](https://api.alpha.ca.gov/StateHolidayCalendar/next).

Staging is now using the service.

**Comment by abquirarte** [comment]
Next Holiday- Feb 17th 🥇
