### ISSUE TITLE
API Service root redirect

### ISSUE THREAD

**Issue by carterm** [cagov/API#3]
Ensure that the root page for the API URL redirects to API documentation.  This will be more useful for public consumers than the default Azure "Hello World" page.

**Comment by carterm** [comment]
https://github.com/cagov/FunctionApps/commit/984cecc5b0d9fdc201c88d4500218744b072b32c

**Comment by carterm** [comment]
[API Site Root](https://fa-go-alph-d-001.azurewebsites.net)
Now redirects to...
[API Doc site](https://documenter.getpostman.com/view/9918160/SWLb8Uep)

**Comment by abquirarte** [comment]
✅
