### ISSUE TITLE
API Service automated testing

### ISSUE THREAD

**Issue by carterm** [cagov/API#5]
We should setup an environment to automatically test that the API Services are running.

**Comment by carterm** [comment]
<img width="1281" alt="Auto Testing" src="https://user-images.githubusercontent.com/6798999/71631161-0242ce00-2bbc-11ea-890f-f35095f64d81.png">

**Comment by carterm** [comment]
Created a Postman project and a monitor service.

Located [Here](https://cadotgov.postman.co/monitors/1ea28ce1-de54-4480-81c9-7b3889ea88d9?workspace=a45921a4-1873-4f96-b06d-48262eec7410)
Limited to 5 users so account required to view.

**Comment by abquirarte** [comment]
👏
