### ISSUE TITLE
API Service for State Holiday Calendars in ICAL (ICS) format

### ISSUE THREAD

**Issue by carterm** [cagov/API#6]
Create a data service for returning the CA State Holidays in ICAL (ICS) format.

**Comment by carterm** [comment]
Service is running, described [here](https://documenter.getpostman.com/view/9918160/SWLb8Uep).

The current link to the download is [here](https://fa-go-alph-d-001.azurewebsites.net/StateHolidayCalendar.ics).

Data is in a Google Calendar.  Located [here](https://calendar.google.com/calendar/r/settings/calendar/YWxwaGEuY2EuZ292X205MzcydWoyMW02cWRncnFnNG9sa2RnbzRjQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).
(Access required)

Sharable public link to the Google Calendar... [here](https://calendar.google.com/calendar?cid=YWxwaGEuY2EuZ292X205MzcydWoyMW02cWRncnFnNG9sa2RnbzRjQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).

**Comment by carterm** [comment]
HTML to download ICAL...

`<a href="https://fa-go-alph-d-001.azurewebsites.net/StateHolidayCalendar.ics" download>Download ICAL</a>`

**Comment by abquirarte** [comment]
✅
