### ISSUE TITLE
API Service for CA State Holidays by year in JSON format

### ISSUE THREAD

**Issue by carterm** [cagov/API#7]
Create an API Service to return a years worth of State Holidays in JSON format.  We can use this to support our own interfaces/components, but the major offering is to allow other state agencies to refer to this data for their own applications, since this data is manually entered all over the state.

- [x] Activate Google API for CA State Holiday Calendar
- [x] Connect API to new service
- [x] Test and monitor

**Comment by carterm** [comment]
Node.JS reference...
https://googleapis.dev/nodejs/googleapis/latest/calendar/classes/Calendar.html

**Comment by abquirarte** [comment]
@aaronhans @carterm still need this? 

Moving to backlog for now until I hear from you both on this.

**Comment by carterm** [comment]
"Next" holiday service is live.
https://github.com/cagov/API/issues/20

**Comment by carterm** [comment]
[Staging](https://staging.alpha.technology.ca.gov/state-california-employee-holidays/) site now uses full list holiday api.

New API [here](https://api.alpha.ca.gov/StateHolidayCalendar/all)

**Comment by carterm** [comment]
Spanish mode API - [here](https://api.alpha.ca.gov/StateHolidayCalendar/all?lang=es)
Chinese mode API - [here](https://api.alpha.ca.gov/StateHolidayCalendar/all?lang=zh)

**Comment by carterm** [comment]
API documented [here](https://documenter.getpostman.com/view/9918160/SWLb8Uep?version=latest)

**Comment by abquirarte** [comment]
Carter still wins best documentation- closing
