### ISSUE TITLE
Create "Always On" API Service

### ISSUE THREAD

**Issue by carterm** [cagov/API#8]
Our currently implementation of the Function as a Service API is "consumption based."  That is the most cost effective way to do development, but sometimes the "cold start" could take up to 15 seconds to get the service running.  That won't be acceptable for production.  Let's create a "production" site that uses the premium "Always On" implementation.

**Comment by carterm** [comment]
<img width="1160" alt="AlwaysOnServiceVerified" src="https://user-images.githubusercontent.com/6798999/71745175-3caba580-2e1e-11ea-8466-333fc6c74d6e.png">

**Comment by carterm** [comment]
Always on service created and verified.  (See image).  All tests combined now consistently run below 4 seconds.

Documentation site updated to use new service urls.

[Doc site](https://documenter.getpostman.com/view/9918160/SWLb8Uep)

[Connection Test site in new environment - fa-go-alph-d-**002**](https://fa-go-alph-d-002.azurewebsites.net/ConnectionTest)

**Comment by carterm** [comment]
Thanks @ChadABratton for your help!

**Comment by carterm** [comment]
Updated State Holiday UX to use new link.

**Comment by abquirarte** [comment]
✅
