### ISSUE TITLE
API Service for CA Cities by Zip Code

### ISSUE THREAD

**Issue by carterm** [cagov/API#9]
Add a service to return CA city by zip code.  This will be used by multiple services including Min Wage.

Create Service - [x ] 
Deploy and Test Service- [x ] 
Switch Min Wage page to use service - [x ] 
Finalize Issue - [x ]

**Comment by carterm** [comment]
https://github.com/cagov/API/pull/10

**Comment by carterm** [comment]
Service deployed!

Pull request with the code listed [here](https://github.com/cagov/API/pull/10).

"CA Zip Lookup" service now listed on document site [here](https://documenter.getpostman.com/view/9918160/SWLb8Uep).

To run the service on the 92274 area code...the link would look like this
`https://api.alpha.ca.gov/caziplookup/92274`
[try it](https://api.alpha.ca.gov/caziplookup/92274)

Staging site uses the real service now...[here](https://staging.alpha.technology.ca.gov/services/find-minimum-wage-your-city/)

**Comment by abquirarte** [comment]
👏
